site_name: rocktemplate
docs_dir: docs
site_dir: site
repo_name: spidernet-io/rocktemplate
repo_url: https://github.com/spidernet-io/rocktemplate
# remote branch for mkdocs gh-deploy
remote_branch: github_pages
theme:
  name: material
  custom_dir: docs/overrides
  # The maximum depth of the navigation tree in the sidebar
  navigation_depth: 2
  palette:
    scheme: default
    primary: blue
    language: zh
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share

plugins:
  - tags
  - search

extra:
  version:
    provider: mike

markdown_extensions:
  - meta
  - toc
  - tables
  - fenced_code
  - tables
  - attr_list

nav:
  - README.md
  - usage:
      - usage: usage/usage.md
  - develop:
      - dev: develop/dev.md
      - release: develop/release.md
