// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetEndpointIDParams creates a new GetEndpointIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetEndpointIDParams() *GetEndpointIDParams {
	return &GetEndpointIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetEndpointIDParamsWithTimeout creates a new GetEndpointIDParams object
// with the ability to set a timeout on a request.
func NewGetEndpointIDParamsWithTimeout(timeout time.Duration) *GetEndpointIDParams {
	return &GetEndpointIDParams{
		timeout: timeout,
	}
}

// NewGetEndpointIDParamsWithContext creates a new GetEndpointIDParams object
// with the ability to set a context for a request.
func NewGetEndpointIDParamsWithContext(ctx context.Context) *GetEndpointIDParams {
	return &GetEndpointIDParams{
		Context: ctx,
	}
}

// NewGetEndpointIDParamsWithHTTPClient creates a new GetEndpointIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetEndpointIDParamsWithHTTPClient(client *http.Client) *GetEndpointIDParams {
	return &GetEndpointIDParams{
		HTTPClient: client,
	}
}

/*
GetEndpointIDParams contains all the parameters to send to the API endpoint

	for the get endpoint ID operation.

	Typically these are written to a http.Request.
*/
type GetEndpointIDParams struct {

	/* ID.

	   String describing an endpoint

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get endpoint ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEndpointIDParams) WithDefaults() *GetEndpointIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get endpoint ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEndpointIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get endpoint ID params
func (o *GetEndpointIDParams) WithTimeout(timeout time.Duration) *GetEndpointIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get endpoint ID params
func (o *GetEndpointIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get endpoint ID params
func (o *GetEndpointIDParams) WithContext(ctx context.Context) *GetEndpointIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get endpoint ID params
func (o *GetEndpointIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get endpoint ID params
func (o *GetEndpointIDParams) WithHTTPClient(client *http.Client) *GetEndpointIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get endpoint ID params
func (o *GetEndpointIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get endpoint ID params
func (o *GetEndpointIDParams) WithID(id string) *GetEndpointIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get endpoint ID params
func (o *GetEndpointIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetEndpointIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
